# Generated by Django 4.1.3 on 2022-11-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresas',
            new_name='Empresa',
        ),
    ]
