# Generated by Django 4.1.3 on 2022-11-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horas_extras', '0003_horaextra_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaextra',
            name='utilizada',
            field=models.BooleanField(default=False),
        ),
    ]
